kind: pipeline
name: build

trigger:
  event:
  - push

steps:
- name: source
  image: ubuntu:bionic
  pull: true
  commands:
  # - apt update && apt-get install -y git curl xz-utils subversion build-essential libncurses5-dev zlib1g-dev gawk gcc-multilib flex gettext libssl-dev unzip wget time python python3 python3-distutils file autoconf&& rm -rf /var/lib/apt/lists/*
  - apt update && apt install -y build-essential --no-install-suggests
  - apt-get install tree -y
  - apt-get install wget -y
  - apt-get install unzip -y
  - apt-get install git -y
  - apt-get install bzip2 -y
  - apt-get install libbz2-dev -y
  - apt-get install libconfig-dev -y
  - apt-get install -y libmodbus-dev -y
  - apt-get install libmbedtls-dev -y
  - apt-get install libmosquitto-dev -y
  - apt-get install curl -y
  - apt-get install xz-utils -y
  - ./source.sh
    
