kind: pipeline
name: build

trigger:
  event:
  - push

# steps:
# - name: source
#   image: ubuntu:bionic
#   pull: true
#   commands:
#   - apt update && apt-get install -y git subversion build-essential libncurses5-dev zlib1g-dev gawk gcc-multilib flex gettext libssl-dev unzip wget time python python3 python3-distutils file autoconf&& rm -rf /var/lib/apt/lists/*
#   - ./source.sh


build:
  image: "sartura/drone-openwrt-builder:arch"
  commands:
    - export FORCE_UNSAFE_CONFIGURE=1
    - make defconfig
    - make -j8